  $fieldable_panels_pane_type = new stdClass();
  $fieldable_panels_pane_type->disabled = FALSE; /* Edit this to true to make a default fieldable_panels_pane_type disabled initially */
  $fieldable_panels_pane_type->api_version = 1;
  $fieldable_panels_pane_type->name = '%machine_name%';
  $fieldable_panels_pane_type->title = '%name%';
  $fieldable_panels_pane_type->description = '';
  $export['%machine_name%'] = $fieldable_panels_pane_type;
